-- =============================================================
-- Script  : 05_grants_dev.sql
-- Purpose : Apply all grants for DEV environment
-- Author  : EBS Migration Project
-- Run As  : SYSADMIN / SECURITYADMIN
-- =============================================================

-- -------------------------------------------------------------
-- SECTION 1: Warehouse grants
-- -------------------------------------------------------------

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE EBS_DEV_DBT_WH
    TO ROLE DEV_DBT_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_AIRFLOW_WH
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_SNOWPIPE_WH
    TO ROLE DEV_SNOWPIPE_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_ANALYST_WH
    TO ROLE EBS_DEV_ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_DATA_ENGINEER_WH
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- SECTION 2: Database grants
-- -------------------------------------------------------------

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_DBT_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_SNOWPIPE_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 3: Schema grants — USAGE
-- -------------------------------------------------------------

-- DEV_DBT_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_DBT_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_DBT_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE DEV_DBT_ROLE;

-- DEV_AIRFLOW_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE DEV_AIRFLOW_ROLE;

-- DEV_SNOWPIPE_ROLE — Bronze only
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

-- EBS_DEV_DATA_ENGINEER_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE — Silver and Gold only
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE — Gold only
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 4: Schema level CREATE privileges for Airflow
-- Airflow needs to create objects as part of pipeline execution
-- -------------------------------------------------------------

GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE
    ON SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT CREATE TABLE
    ON SCHEMA DEV_DB.EBS_SILVER
    TO ROLE DEV_AIRFLOW_ROLE;

-- -------------------------------------------------------------
-- SECTION 5: Table grants
-- -------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- DEV_DBT_ROLE — SELECT Bronze, FULL Silver and Gold
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_DBT_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_DBT_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_DBT_ROLE;

-- DEV_SNOWPIPE_ROLE — FULL Bronze only
GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

-- DEV_AIRFLOW_ROLE — SELECT all layers
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_AIRFLOW_ROLE;

-- EBS_DEV_DATA_ENGINEER_ROLE — FULL all layers
GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE — SELECT Silver and Gold
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE — SELECT Gold only
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 6: Stage grants
-- -------------------------------------------------------------

GRANT ALL PRIVILEGES ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT READ, OPERATE ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT READ, OPERATE ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

-- -------------------------------------------------------------
-- SECTION 7: Pipe grants
-- -------------------------------------------------------------

GRANT OPERATE, ALTER ON ALL PIPES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT OPERATE, ALTER ON FUTURE PIPES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

GRANT ALL PRIVILEGES ON ALL PIPES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PIPES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

-- -------------------------------------------------------------
-- SECTION 8: Stream grants
-- -------------------------------------------------------------

GRANT SELECT, OPERATE ON ALL STREAMS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT, OPERATE ON FUTURE STREAMS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

GRANT SELECT, OPERATE ON ALL STREAMS
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT, OPERATE ON FUTURE STREAMS
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;

GRANT ALL PRIVILEGES ON ALL STREAMS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- SECTION 9: Task grants
-- -------------------------------------------------------------

GRANT OPERATE, EXECUTE TASK ON ALL TASKS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT OPERATE, EXECUTE TASK ON FUTURE TASKS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

GRANT OPERATE, EXECUTE TASK ON ALL TASKS
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;
GRANT OPERATE, EXECUTE TASK ON FUTURE TASKS
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;

GRANT ALL PRIVILEGES ON ALL TASKS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- VERIFICATION
-- -------------------------------------------------------------

SHOW GRANTS TO ROLE DEV_DBT_ROLE;
SHOW GRANTS TO ROLE DEV_AIRFLOW_ROLE;
SHOW GRANTS TO ROLE DEV_SNOWPIPE_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_SR_ANALYST_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_ANALYST_ROLE;
