-- =============================================================
-- Script  : 05_grants_dev.sql
-- Purpose : Apply all grants for DEV environment
-- Author  : EBS Migration Project
-- Run As  : SYSADMIN / SECURITYADMIN
-- =============================================================

-- -------------------------------------------------------------
-- SECTION 1: Warehouse grants
-- -------------------------------------------------------------

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE EBS_DEV_DBT_WH
    TO ROLE DEV_DBT_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_AIRFLOW_WH
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_SNOWPIPE_WH
    TO ROLE DEV_SNOWPIPE_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_ANALYST_WH
    TO ROLE EBS_DEV_ANALYST_ROLE;

GRANT USAGE ON WAREHOUSE EBS_DEV_DATA_ENGINEER_WH
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- SECTION 2: Database grants
-- -------------------------------------------------------------

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_DBT_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_SNOWPIPE_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 3: Schema grants — USAGE
-- -------------------------------------------------------------

-- DEV_DBT_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_DBT_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_DBT_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE DEV_DBT_ROLE;

-- DEV_AIRFLOW_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE DEV_AIRFLOW_ROLE;

-- DEV_SNOWPIPE_ROLE — Bronze only
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

-- EBS_DEV_DATA_ENGINEER_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE — Silver and Gold only
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE — Gold only
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD   TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 4: Schema level CREATE privileges for Airflow
-- Airflow needs to create objects as part of pipeline execution
-- -------------------------------------------------------------

GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE
    ON SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT CREATE TABLE
    ON SCHEMA DEV_DB.EBS_SILVER
    TO ROLE DEV_AIRFLOW_ROLE;

-- -------------------------------------------------------------
-- SECTION 5: Table grants
-- -------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- DEV_DBT_ROLE — SELECT Bronze, FULL Silver and Gold
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_DBT_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_DBT_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_DBT_ROLE;

-- DEV_SNOWPIPE_ROLE — FULL Bronze only
GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

-- DEV_AIRFLOW_ROLE — SELECT all layers
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE DEV_AIRFLOW_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_AIRFLOW_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE DEV_AIRFLOW_ROLE;

-- EBS_DEV_DATA_ENGINEER_ROLE — FULL all layers
GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE — SELECT Silver and Gold
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE — SELECT Gold only
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 6: Stage grants
-- -------------------------------------------------------------
-- Snowpipe role — full stage access (READ + WRITE)
GRANT READ, WRITE ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;
GRANT READ, WRITE ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_SNOWPIPE_ROLE;

-- Data engineer — full stage access
GRANT READ, WRITE ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT READ, WRITE ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- Airflow — READ only on stage
GRANT READ ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;
GRANT READ ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE TO ROLE DEV_AIRFLOW_ROLE;

-- -------------------------------------------------------------
-- SECTION 7: Pipe grants
-- Pipe grants are handled at pipe creation time
-- not at foundation setup level
-- Reason: Snowflake restricts bulk grants on pipes
--         Least privilege — grant per pipe when created
-- See: snowflake/sql/bronze/ingestion_pipes.sql
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- SECTION 8: Stream grants
-- Stream grants are handled at stream creation time
-- not at foundation setup level
-- Reason: Snowflake restricts bulk grants on streams
--         Least privilege — grant per stream when created
-- See: snowflake/sql/bronze/cdc_streams.sql
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- SECTION 9: Task grants
-- Task grants are handled at task creation time
-- not at foundation setup level
-- Reason: Snowflake restricts bulk grants on tasks
--         Least privilege — grant per task when created
-- See: snowflake/sql/bronze/cdc_tasks.sql
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- VERIFICATION
-- -------------------------------------------------------------

SHOW GRANTS TO ROLE DEV_DBT_ROLE;
SHOW GRANTS TO ROLE DEV_AIRFLOW_ROLE;
SHOW GRANTS TO ROLE DEV_SNOWPIPE_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_SR_ANALYST_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_ANALYST_ROLE;
