-- =============================================================
-- Script  : 05_grants_dev.sql
-- Purpose : Apply all grants for DEV environment
-- Author  : EBS Migration Project
-- Run As  : SECURITYADMIN / SYSADMIN
-- =============================================================

-- -------------------------------------------------------------
-- SECTION 1: Warehouse grants
-- Granted at Tier 2 source role level
-- -------------------------------------------------------------

USE ROLE SYSADMIN;

-- dbt warehouse → EBS DEV DBT role
GRANT USAGE ON WAREHOUSE EBS_DEV_DBT_WH
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- Airflow warehouse → EBS DEV Airflow role
GRANT USAGE ON WAREHOUSE EBS_DEV_AIRFLOW_WH
    TO ROLE DEV_AIRFLOW_ROLE;

-- Snowpipe warehouse → EBS DEV Snowpipe role
GRANT USAGE ON WAREHOUSE EBS_DEV_SNOWPIPE_WH
    TO ROLE DEV_SNOWPIPE_ROLE;

-- Analyst warehouse → EBS DEV Analyst role
GRANT USAGE ON WAREHOUSE EBS_DEV_ANALYST_WH
    TO ROLE EBS_DEV_ANALYST_ROLE;

-- Data engineer warehouse → EBS DEV Data Engineer role
GRANT USAGE ON WAREHOUSE EBS_DEV_DATA_ENGINEER_WH
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- SECTION 2: Database grants
-- USAGE on DEV_DB for all roles
-- -------------------------------------------------------------

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE EBS_DEV_ANALYST_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_AIRFLOW_ROLE;

GRANT USAGE ON DATABASE DEV_DB
    TO ROLE DEV_SNOWPIPE_ROLE;

-- -------------------------------------------------------------
-- SECTION 3: Schema grants
-- USAGE on all three schemas for each role
-- -------------------------------------------------------------

-- EBS_DEV_DATA_ENGINEER_ROLE — full access all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE — Silver and Gold only
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE — Gold only
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_ANALYST_ROLE;

-- DEV_AIRFLOW_ROLE — all schemas
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE DEV_AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_SILVER
    TO ROLE DEV_AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.EBS_GOLD
    TO ROLE DEV_AIRFLOW_ROLE;

-- DEV_SNOWPIPE_ROLE — Bronze only
GRANT USAGE ON SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE DEV_SNOWPIPE_ROLE;

-- -------------------------------------------------------------
-- SECTION 4: Table grants — existing + future
-- -------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- EBS_DEV_DATA_ENGINEER_ROLE — full access all layers
GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE — SELECT on Silver and Gold
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE — SELECT on Gold only
GRANT SELECT ON ALL TABLES
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 5: View grants — existing + future
-- -------------------------------------------------------------

-- EBS_DEV_DATA_ENGINEER_ROLE
GRANT ALL PRIVILEGES ON ALL VIEWS
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL VIEWS
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL VIEWS
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- EBS_DEV_SR_ANALYST_ROLE
GRANT SELECT ON ALL VIEWS
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS
    IN SCHEMA DEV_DB.EBS_SILVER
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

GRANT SELECT ON ALL VIEWS
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_SR_ANALYST_ROLE;

-- EBS_DEV_ANALYST_ROLE
GRANT SELECT ON ALL VIEWS
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS
    IN SCHEMA DEV_DB.EBS_GOLD
    TO ROLE EBS_DEV_ANALYST_ROLE;

-- -------------------------------------------------------------
-- SECTION 6: Stage grants — Bronze only for Snowpipe
-- -------------------------------------------------------------

GRANT ALL PRIVILEGES ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE DEV_SNOWPIPE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE DEV_SNOWPIPE_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- SECTION 7: Stream and Task grants
-- -------------------------------------------------------------

GRANT ALL PRIVILEGES ON ALL STREAMS
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON ALL TASKS
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS
    IN SCHEMA DEV_DB.EBS_BRONZE
    TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;

-- -------------------------------------------------------------
-- VERIFICATION
-- -------------------------------------------------------------

SHOW GRANTS TO ROLE EBS_DEV_DATA_ENGINEER_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_ANALYST_ROLE;
SHOW GRANTS TO ROLE EBS_DEV_SR_ANALYST_ROLE;
